config/routes.rb
Rails.application.routes.draw do
  get 'what_is/index'
  get 'about/index'
  get 'contact/index'
  get 'topbar/index'
  get 'footer/index'
  get 'gana_mas/index'
  get 'gana_acompana/index'
  get 'gana_navega/index'
  get 'gana_arranca/index'
  get 'gana_genera/index'
  # get 'home/index'
  root 'government#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/citizen_controller.rb
class CitizenController < ApplicationController
  def index
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/footer_controller.rb
class FooterController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def redirect
    # redirect_to 
  end
end

app/controllers/topbar_controller.rb
class TopbarController < ApplicationController
  def index
  end
end

app/controllers/what_is_controller.rb
class WhatIsController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/citizen_helper.rb
module CitizenHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/footer_helper.rb
module FooterHelper
end

app/helpers/gana_acompana_helper.rb
module GanaAcompanaHelper
end

app/helpers/gana_arranca_helper.rb
module GanaArrancaHelper
end

app/helpers/gana_genera_helper.rb
module GanaGeneraHelper
end

app/helpers/gana_mas_helper.rb
module GanaMasHelper
end

app/helpers/gana_navega_helper.rb
module GanaNavegaHelper
end

app/helpers/government_helper.rb
module GovernmentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/topbar_helper.rb
module TopbarHelper
end

app/helpers/what_is_helper.rb
module WhatIsHelper
end

app/views/about/index.html.erb
<%= render template: "topbar/index" %>
<%= image_tag("WEB-GANA-LOGO", class: "logo") %>
<%= image_tag("WEB-GANA-EQUIPO", class: "background-equipo") %>
<%= image_tag("WEB-GANA-TEAM", class: "background-team") %>
<%= render template: "footer/index" %>

app/views/contact/index.html.erb
<%= render template: "topbar/index" %>
<%= image_tag("WEB-GANA-111", class: "background-contact") %>
<%= render template: "footer/index" %>

app/views/home/index.html.erb
<%= content_tag(:div, class: "main-te") do %>
  <%= image_tag("logo-white-gana", class: "logo-img") %>
  <%= content_tag(:div, class: "description") do %>
    <%= content_tag(:p, "¿Qué es?", class: "paragraph-logo") %>
    <%= content_tag(:p, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled", class: "paragraph-description") %>
  <% end %>

  <%= image_tag("WEB-GANA-77", class: "img-inicia") %>

  <%= content_tag(:div, class: "div-buttons") do %>
    <%= content_tag(:div, class: "div-gov") do %>
    <%= link_to government_index_path, id: "btn-gov" do %>
      <%= image_tag("1-15") %>
    <% end %>
    <hr />
    <%= content_tag(:p, "Gobierno") %>
  <% end %>

  <%= content_tag(:div, class: "div-citizen") do %>
    <%= link_to citizen_index_path, id: "btn-citizen" do %>
        <%= image_tag("1-16") %>
    <% end %>
    <hr />
    <%= content_tag(:p, "Ciudadanía") %>
    <% end %>
  <% end %>
<% end %>

app/views/topbar/index.html.erb
<%= content_tag(:div, class: "topbar") do %>

  <%= content_tag(:div, class: "logo-gana") do %>
    <%= link_to root_path do %>
      <%= image_tag("WEB-GANA-49") %>
    <% end %>
  <% end %>

  <%= content_tag(:div, class: "links-gana") do %>
    <%= link_to contact_index_path do %>
      <b>Contacto</b>
    <% end %>
    <%= link_to about_index_path do %>
      <b>Nosotros</b>
    <% end %>
    <%= link_to what_is_index_path do %>
      <b>¿Que és?</b>
    <% end %>
  <% end %>
<% end %>

app/views/what_is/index.html.erb
<%= render template: "topbar/index" %>
<%= image_tag("WEB-GANA-110", class: "background-what-is") %>
<%= render template: "footer/index" %>