config/routes.rb
Rails.application.routes.draw do
  get 'what_is/index'
  get 'about/index'
  get 'contact/index'
  get 'topbar/index'
  get 'footer/index'
  get 'gana_mas/index'
  get 'gana_acompana/index'
  get 'gana_navega/index'
  get 'gana_arranca/index'
  get 'gana_genera/index'
  # get 'home/index'
  root 'government#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/citizen_controller.rb
class CitizenController < ApplicationController
  def index
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/footer_controller.rb
class FooterController < ApplicationController
  def index
  end
end

app/controllers/gana_arranca_controller.rb
class GanaArrancaController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def redirect
    # redirect_to 
  end
end

app/controllers/topbar_controller.rb
class TopbarController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/citizen_helper.rb
module CitizenHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/footer_helper.rb
module FooterHelper
end

app/helpers/gana_acompana_helper.rb
module GanaAcompanaHelper
end

app/helpers/gana_arranca_helper.rb
module GanaArrancaHelper
end

app/helpers/gana_genera_helper.rb
module GanaGeneraHelper
end

app/helpers/gana_mas_helper.rb
module GanaMasHelper
end

app/helpers/gana_navega_helper.rb
module GanaNavegaHelper
end

app/helpers/government_helper.rb
module GovernmentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/topbar_helper.rb
module TopbarHelper
end

app/helpers/what_is_helper.rb
module WhatIsHelper
end

app/views/gana_arranca/index.html.erb
<%= render template: "topbar/index" %>

<%= content_tag(:div, class: "main-arranca") do %>
  <%= content_tag(:div, class: "gana-arranca-div") do %>
    <%= link_to gana_genera_index_path do %>
      <div class="gana-arranca-g">
      </div>
    <% end %>
    <%= link_to gana_arranca_index_path do %>
      <div class="gana-arranca-a1">
      </div>
    <% end %>
    <%= link_to gana_navega_index_path do %>
      <div class="gana-arranca-n">
      </div>
    <% end %>
    <%= link_to gana_acompana_index_path do %>
      <div class="gana-arranca-a2">
      </div>
    <% end %>
      <div class="gana-arranca-mas">
      </div>
  <% end %>
  <p>Kit de <b>herramientas</b> para Presupuestos Participativos</p>

  <hr class="arranca-hr1">

  <%= content_tag(:div, class: "first-step") do %>
    <%= content_tag(:div, class: "image-first-step") do %>
      <div class="gana-arranca-first-step"></div>
    <% end %>

    <%= content_tag(:div, class: "text-first-step") do %>
      <h3>Estamos en la segunda instancia.</h3>
      <%= content_tag(:p, "Vamos a co-diseñar propuestas para invertir nuestros recursos y empoderar a la ciudadanía en un proceso colectivo de trabajo.") %>
      <%= image_tag("WEB-GANA-81") %>
    <% end %>
  <% end %>

  <hr class="arranca-hr2">
  <%= content_tag(:div, class: "genera-second-step") do %>
    <%= content_tag(:div, class: "second-step-flex") do %>
      <%= content_tag(:div, class: "images-genera-second-step") do %>
        <%= image_tag("barrra-84", class: "background-blue") %>
        <%= content_tag(:div, class: "img-genera-secon-step") do %>
          <%= image_tag("WEB-GANA-83", class: "arranca-herramientas") %>
          <%= image_tag("WEB-GANA-84", class: "gana-mas-image") %>
        <% end %>
      <% end %>
      <%= content_tag(:div, class: "second-arranca-step-content") do %>
        <%= image_tag("WEB-GANA-87", class: "title-arranca-second-step") %>
        <%= content_tag(:p, "Vamos a aprender a elaborar la comunicación del proceso.") %>
      <% end %>
    <% end %>

    <%= content_tag(:div, class: "blue-genera-second-step") do %>
      <div class="background-arranca-second-step">
      </div>
    <% end %>
    <%= content_tag(:div, class: "descarga-second-step") do %>
    <%= image_tag("2-88") %>
    <%= image_tag("1-79") %>
    <% end %>
  <% end %>

  <hr class="hr3">

  <%= content_tag(:div, class: "genera-fourth-step") do %>
    <%= content_tag(:div, class: "second-step-flex") do %>
      <%= content_tag(:div, class: "images-genera-second-step") do %>
        <%= image_tag("barrra-84", class: "background-blue") %>
        <%= content_tag(:div, class: "img-arranca-secon-step") do %>
          <%= image_tag("WEB-GANA-95", class: "gana-mas-proyecto-image") %>
        <% end %>
      <% end %>
      <%= content_tag(:div, class: "second-arranca-step-content") do %>
        <%= image_tag("WEB-GANA-97", class: "title-arranca-second-step") %>
        <%= content_tag(:p, " Vamos a conformar una guía para la elaboración de proyectos de Presupuestos Participativo.") %>
      <% end %>
    <% end %>

    <%= content_tag(:div, class: "blue-genera-second-step") do %>
      <div class="background-arranca-second-step">
      </div>
    <% end %>
    <%= content_tag(:div, class: "descarga-second-step") do %>
    <%= image_tag("2-88") %>
    <%= image_tag("1-79") %>
    <% end %>
  <% end %>

  <hr class="hr3">

  <%= content_tag(:div, class: "gana-actores") do %>
    <%= content_tag(:div, class: "gana-actores-title") do %>
      <%= content_tag(:div, class: "arranca-title-actores") do %>
        <%= image_tag("WEB-GANA-98", class: "name-arranca-title-fuerza") %>
        <p>Prepararemos el proceso de deliberación previo a la votación.</p>
      <% end %>
      <%= image_tag("WEB-GANA-96", class: "personas-title-actors") %>
    <% end %>

    <%= content_tag(:div, class: "blue-genera-third-step") do %>
      <div class="background-arranca-third-step">
      </div>
    <% end %>
    <%= content_tag(:div, class: "descarga-third-step") do %>
      <%= image_tag("2-88") %>
      <%= image_tag("1-79") %>
    <% end %>
  <% end %>

  <hr class="hr4">

  <%= image_tag("barrra-84", class: "background-blue-footer") %>

  <%= content_tag(:div, class: "genera-footer-block") do %>
    <%= content_tag(:div, class: "genera-footer") do %>
      <%= link_to gana_genera_index_path do %>
        <div class="gana-arranca-g"></div>
        <p>1</p>
      <% end %>
      <%= link_to gana_arranca_index_path do %>
        <div class="gana-arranca-a1">
        </div>
        <p>2</p>
      <% end %>
      <%= link_to gana_navega_index_path do %>
        <div class="gana-arranca-n">
        </div>
        <p>3</p>
      <% end %>
      <%= link_to gana_acompana_index_path do %>
        <div class="gana-arranca-a2">
        </div>
        <p>4</p>
      <% end %>
        <div class="gana-arranca-mas">
        </div>

    <% end %>
    <p style="color: #0b8a36; margin-right: 5%;"><b>¡Genial!</b></p>
    <p style="width: 40%; font-size: 13px;margin:auto;">Te invitamos a pasar a la seguinte etapa.<br>No olvides dar check en tu <b>Lienzo de Presupuestos Participativos</b> y compartir tu experiencia en redes sociales con el <b>#ganamas</b></p>
  <% end %>
<% end %>

<%= render template: "footer/index" %>